"""Build #10 — THE PUBLISHED-PORT INVARIANT.

Build #9's live-fire task 4 could not complete because the engage sandbox publishes NO ports:
the DC has no route to a Docker bridge, so a beacon had nowhere to call back to. The honest
answer recorded then was "publishing a port changes the sandbox's network posture, so the
compose change was not made".

Build #10 makes that change — and this file is the fence around it. The rule is not "no
exposure ever"; it is:

  1. THE DEFAULT POSTURE PUBLISHES NOTHING. `docker compose -f docker/docker-compose.yml up`
     must expose zero ports on the host. Someone who brings the stack up the documented way
     gets exactly what they got before build #10. Exposure is never the default.

  2. EXPOSURE IS OPT-IN AND LIVES IN ITS OWN FILE. It is reachable only by explicitly adding
     a second `-f`. A reviewer can see the whole exposure surface by reading one small file.

  3. EVERY PUBLISHED PORT IS BOUND TO ONE HOST IP. `"53:53/udp"` and `"0.0.0.0:53:53/udp"`
     bind EVERY interface on the machine — including whatever Wi-Fi the laptop is on. This is
     the check that keeps "my DC can reach the listener" from silently meaning "so can the
     coffee-shop network".

BUILD #13 AMENDS 2 AND 3, AND THE AMENDMENT IS THE INTERESTING PART.

The exposure is now GENERATED by cockpit/exposure.py rather than hand-written, so invariant 2
follows the generated path (`docker/listener-profile.yml`) instead of the one file build #10
wrote. That file is gitignored — it can hold a client's internal address and this repository is
public — so on a clean checkout it does not exist. `backend/test_support/c2-lab.golden.yml` is
build #10's file kept as a fixture, so invariant 3 always has something real to run against
rather than passing vacuously.

Invariant 3 no longer REFUSES a wildcard or public bind. Both are red-confirms now, matching
the danger gate's own rule that it "never blocks outright; requires the confirm". But an
acknowledgement only counts if a static scan can see it, so it is written INTO the file as a
`# hackpit-ack: <why> bind=<ip> ...` line, and the rule becomes COVERED rather than ABSENT —
each broad binding needs a marker naming that EXACT address. Without that, permitting an
acknowledged wildcard would have deleted this invariant rather than relaxing it.

WHY A TEXT SCAN AND NOT A YAML PARSE: the hermetic suite must run with no third-party deps
(the same property that keeps pywinrm out of it). Compose port entries are a simple list of
scalars, so a line scan reads them exactly, and a malformed file fails loudly rather than
being silently normalised by a parser. For the same reason the private-range check here reads
the literal quad instead of importing cockpit.exposure: a scanner that imports the code it
polices can be disarmed by editing that code.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_COMPOSE = REPO / "docker" / "docker-compose.yml"
# Build #13: the exposure is GENERATED (cockpit/exposure.py) rather than hand-written, so the
# live path is the generated file. It is gitignored, so on a clean checkout it does not exist —
# and a check that is vacuous on a clean checkout is not a check. GOLDEN is the file build #10
# hand-wrote, kept as a fixture, so the rules below always have something real to run against.
EXPOSURE_OVERRIDE = REPO / "docker" / "listener-profile.yml"
GOLDEN = REPO / "backend" / "test_support" / "c2-lab.golden.yml"


def _exposure_files() -> list[Path]:
    return [p for p in (EXPOSURE_OVERRIDE, GOLDEN) if p.exists()]

# A published-port entry that names a host IP: "<ip>:<hostport>:<containerport>[/proto]".
# The IP must be a literal dotted quad — a name would resolve at `up` time to who-knows-what.
_IP_BOUND = re.compile(r"^(?P<ip>\d{1,3}(?:\.\d{1,3}){3}):(?P<host>\d+):(?P<cont>\d+)(?:/(?P<proto>tcp|udp))?$")

# The bindings that mean "every interface on this machine".
_WILDCARD_IPS = {"0.0.0.0", "::", "*"}


def _strip_comment(line: str) -> str:
    """Compose allows trailing `# ...`. Only strip it outside quotes."""
    out, quote = [], None
    for ch in line:
        if quote:
            out.append(ch)
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
            out.append(ch)
        elif ch == "#":
            break
        else:
            out.append(ch)
    return "".join(out).rstrip()


def published_ports(path: Path) -> list[tuple[int, str]]:
    """Every entry under a `ports:` key, as (line_number, value).

    Handles the two forms compose accepts for a scalar list:
        ports:
          - "1.2.3.4:80:80"
        ports: ["1.2.3.4:80:80"]
    """
    if not path.exists():
        return []
    found: list[tuple[int, str]] = []
    in_ports = False
    ports_indent = -1
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = _strip_comment(raw)
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        stripped = line.strip()

        if in_ports:
            # A list item deeper than the `ports:` key belongs to it.
            if stripped.startswith("-") and indent > ports_indent:
                found.append((lineno, stripped.lstrip("-").strip().strip("\"'")))
                continue
            # Anything at or above the key's indent ends the block.
            if indent <= ports_indent:
                in_ports = False

        m = re.match(r"^ports:\s*(.*)$", stripped)
        if m and not stripped.startswith("-"):
            inline = m.group(1).strip()
            if inline.startswith("["):
                for item in inline.strip("[]").split(","):
                    item = item.strip().strip("\"'")
                    if item:
                        found.append((lineno, item))
            else:
                in_ports = True
                ports_indent = indent
    return found


# The marker that makes a DELIBERATE broad bind auditable (build #13). Kept textually in step
# with cockpit/exposure.ACK_RE — both read the same line out of the same generated file.
_ACK = re.compile(
    r"^#\s*hackpit-ack:\s*(?P<why>wildcard|public)\s+bind=(?P<ip>\S+)\s+engagement=(?P<eng>\S+)"
)

# Private-range prefixes, read off the literal quad. Deliberately NOT imported from
# cockpit.exposure: this file's whole promise is that it depends on nothing but the standard
# library, and a scanner that imports the code it polices can be disarmed by editing that code.
_PRIVATE_PREFIXES = ("10.", "127.", "192.168.", "169.254.")


def _is_private_quad(ip: str) -> bool:
    if ip.startswith(_PRIVATE_PREFIXES):
        return True
    parts = ip.split(".")
    if len(parts) != 4 or not all(p.isdigit() for p in parts):
        return False
    first, second = int(parts[0]), int(parts[1])
    if first == 172 and 16 <= second <= 31:
        return True
    if first == 100 and 64 <= second <= 127:  # CGNAT / Tailscale
        return True
    return False


def acks(path: Path) -> list[tuple[str, str]]:
    """Every `hackpit-ack` marker in the file, as (why, bind_ip)."""
    if not path.exists():
        return []
    out = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        m = _ACK.match(raw.strip())
        if m:
            out.append((m.group("why"), m.group("ip")))
    return out


def unacknowledged_broad_binds(path: Path) -> list[tuple[int, str]]:
    """Published bindings that are wildcard or public and NOT covered by a matching ack.

    Build #10's invariant 3 refused every wildcard outright. Build #13 permits one behind an
    explicit acknowledgement, so the rule becomes COVERED, not ABSENT — and the ack must name
    the EXACT address published. A marker for some other address covers nothing, which is the
    case that keeps this from degrading into "contains the string hackpit-ack somewhere".
    """
    acked = {ip for _why, ip in acks(path)}
    bad: list[tuple[int, str]] = []
    for lineno, entry in published_ports(path):
        m = _IP_BOUND.match(entry)
        ip = m.group("ip") if m else entry.split(":")[0]
        if not m and ip not in _WILDCARD_IPS:
            bad.append((lineno, entry))          # not IP-bound at all — invariant 3, unchanged
            continue
        broad = (ip in _WILDCARD_IPS) or not _is_private_quad(ip)
        if broad and ip not in acked:
            bad.append((lineno, entry))
    return bad


def test_default_compose_publishes_nothing() -> None:
    """Invariant 1. The documented bring-up exposes zero ports."""
    assert DEFAULT_COMPOSE.exists(), f"missing {DEFAULT_COMPOSE}"
    offenders = published_ports(DEFAULT_COMPOSE)
    assert not offenders, (
        "docker/docker-compose.yml publishes ports — the DEFAULT posture must expose nothing. "
        f"Move them into {EXPOSURE_OVERRIDE.name}. Offenders: {offenders}"
    )
    print("  default compose publishes NO ports (exposure is never the default): PASS")


def test_exposure_override_is_ip_bound() -> None:
    """Invariant 3, as amended by build #13.

    Every published port must name a host IP, and any binding that is wildcard or publicly
    routable must be COVERED by a `hackpit-ack` line naming that exact address. A broad bind is
    now a red-confirm rather than a refusal — the pattern the danger gate already uses — but the
    acknowledgement has to be visible to a static scan, or permitting it would delete this
    invariant instead of relaxing it.
    """
    files = _exposure_files()
    assert files, (
        f"neither {EXPOSURE_OVERRIDE.name} nor the golden fixture exists — this check would be "
        "vacuous, which is the one thing it must never be silently"
    )
    total = 0
    for path in files:
        entries = published_ports(path)
        assert entries, (
            f"{path.name} exists but publishes nothing — either it is dead weight or the scan "
            "is not seeing its ports. Both are bugs."
        )
        offenders = unacknowledged_broad_binds(path)
        assert not offenders, (
            f"{path.name} publishes {offenders} — a binding that is not IP-bound, or one that "
            "is wildcard/public without a `# hackpit-ack: <why> bind=<ip> ...` line naming that "
            "exact address."
        )
        total += len(entries)
    shown = ", ".join(p.name for p in files)
    print(f"  every published port is IP-bound or acknowledged ({total} in {shown}): PASS")


def test_override_is_not_wired_into_the_default_path() -> None:
    """Invariant 2. Nothing in the repo brings the override up implicitly.

    A helper script that quietly appends `-f docker/proof/c2-lab.yml` to the normal bring-up
    would defeat invariant 1 without touching docker-compose.yml. The exposure has to be typed
    on purpose, every time.
    """
    # Deliberately NOT skipped when the file is absent. The generated profile is gitignored, so
    # on a clean checkout it never exists — and a script that composes it up is committed
    # whether or not the file is. Skipping here would make this invariant vacuous exactly where
    # a reviewer is most likely to be reading: a fresh clone.
    needle = EXPOSURE_OVERRIDE.name
    # The override may name itself; its own proof script and the module that GENERATES it may
    # compose it deliberately. Anything ELSE that composes it up is what this guards against.
    allowed = {
        EXPOSURE_OVERRIDE.resolve(),
        (REPO / "docker" / "proof" / "c2_lab_proof.sh").resolve(),
        (REPO / "backend" / "cockpit" / "exposure.py").resolve(),
    }
    offenders: list[str] = []
    for path in REPO.rglob("*"):
        if not path.is_file() or path.resolve() in allowed:
            continue
        if any(part in {".git", "node_modules", ".venv", "__pycache__"} for part in path.parts):
            continue
        if path.suffix.lower() not in {".sh", ".yml", ".yaml", ".ps1", ".py", ".bat", ".cmd"}:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if needle not in text:
            continue
        # Documentation and this very test may NAME the file; only an actual `docker compose`
        # invocation that composes it in is an offender.
        for lineno, line in enumerate(text.splitlines(), start=1):
            if needle in line and "compose" in line and "-f" in line:
                offenders.append(f"{path.relative_to(REPO)}:{lineno}")
    assert not offenders, (
        "the opt-in exposure override is composed up by something other than its own proof "
        f"script — exposure must be explicit every time. Offenders: {offenders}"
    )
    print("  no script silently composes the exposure override into the default bring-up: PASS")


def test_ack_marker_must_cover_the_exact_bind() -> None:
    """The four cases invariant 3 now rests on (build #13).

    Permitting an acknowledged wildcard is only safe if "acknowledged" is something a static
    scan can verify. These plant each shape into a temp file and assert the rule, so the rule
    is proven rather than assumed — the same discipline test_scans applies to the source
    scanner it guards.
    """
    import tempfile

    def probe(text: str) -> list[tuple[int, str]]:
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "listener-profile.yml"
            p.write_text(text, encoding="utf-8")
            return unacknowledged_broad_binds(p)

    covered = (
        "services:\n  engage-sandbox:\n"
        "    # hackpit-ack: wildcard  bind=0.0.0.0  engagement=e-1  at=t\n"
        '    ports:\n      - "0.0.0.0:4444:4444/tcp"\n'
    )
    assert probe(covered) == [], probe(covered)

    missing = 'services:\n  engage-sandbox:\n    ports:\n      - "0.0.0.0:4444:4444/tcp"\n'
    assert probe(missing), "an unacknowledged wildcard must fail"

    wrong_ip = (
        "services:\n  engage-sandbox:\n"
        "    # hackpit-ack: wildcard  bind=10.0.0.1  engagement=e-1  at=t\n"
        '    ports:\n      - "0.0.0.0:4444:4444/tcp"\n'
    )
    assert probe(wrong_ip), "an ack naming a different address must not cover this bind"

    public_covered = (
        "services:\n  engage-sandbox:\n"
        "    # hackpit-ack: public  bind=8.8.8.8  engagement=e-1  at=t\n"
        '    ports:\n      - "8.8.8.8:443:443/tcp"\n'
    )
    assert probe(public_covered) == [], probe(public_covered)

    public_missing = 'services:\n  x:\n    ports:\n      - "8.8.8.8:443:443/tcp"\n'
    assert probe(public_missing), "an unacknowledged public bind must fail"

    private_needs_nothing = 'services:\n  x:\n    ports:\n      - "192.168.13.1:53:53/udp"\n'
    assert probe(private_needs_nothing) == [], probe(private_needs_nothing)

    print("  a broad bind must be covered by an ack naming that exact address: PASS")


def test_the_scanner_actually_catches_a_wildcard() -> None:
    """The three tests above all print PASS when they work AND when the scan is broken.

    Same discipline as test_scans.py: plant a violation and prove the parser sees it. Without
    this, a `published_ports` that silently returns [] would make every check above vacuous.
    """
    import tempfile  # noqa: PLC0415

    planted = (
        "services:\n"
        "  engage-sandbox:\n"
        "    ports:\n"
        '      - "0.0.0.0:53:53/udp"\n'
        '      - "8888:8888"\n'
    )
    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / "planted.yml"
        probe.write_text(planted, encoding="utf-8")
        entries = published_ports(probe)
        assert len(entries) == 2, f"the port scanner missed a planted entry: {entries}"
        assert entries[0][1] == "0.0.0.0:53:53/udp", entries
        assert entries[1][1] == "8888:8888", entries
        # And the bind rule rejects both.
        assert _IP_BOUND.match(entries[1][1]) is None, "a bare host:container must not pass"
        m = _IP_BOUND.match(entries[0][1])
        assert m and m.group("ip") in _WILDCARD_IPS, "0.0.0.0 must be recognised as a wildcard"

    # And an inline-list form, which the block scanner must not miss.
    with tempfile.TemporaryDirectory() as tmp:
        probe = Path(tmp) / "inline.yml"
        probe.write_text('services:\n  x:\n    ports: ["0.0.0.0:1:1"]\n', encoding="utf-8")
        assert published_ports(probe) == [(3, "0.0.0.0:1:1")], published_ports(probe)

    print("  the port scanner catches planted wildcard/bare/inline bindings: PASS")


if __name__ == "__main__":
    print("== published-port exposure invariants (build #10, amended #13) ==")
    test_the_scanner_actually_catches_a_wildcard()
    test_ack_marker_must_cover_the_exact_bind()
    test_default_compose_publishes_nothing()
    test_exposure_override_is_ip_bound()
    test_override_is_not_wired_into_the_default_path()
    print("all exposure-invariant tests passed")
    sys.exit(0)
