"use client";

import { useEffect, useState } from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSanitize from "rehype-sanitize";
import { getLLMConfig, getSession, type Session } from "@/lib/api";
import { useApi } from "@/lib/useApi";

function fmtDate(iso: string | null): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleString(undefined, {
    dateStyle: "long",
    timeStyle: "short",
  });
}

// Print-friendly markdown: light code blocks, no copy buttons, images omitted
// (reports are text). Our code element renders its own <pre>, so unwrap theirs.
const components: Components = {
  pre: ({ children }) => <>{children}</>,
  code({ className, children }) {
    const text = String(children ?? "").replace(/\n$/, "");
    const isBlock = /language-/.test(className ?? "") || text.includes("\n");
    if (!isBlock) {
      return <code className="hp-print-code-inline">{children}</code>;
    }
    return (
      <pre className="hp-print-code">
        <code>{text}</code>
      </pre>
    );
  },
  a: ({ children, href }) => <a href={href}>{children}</a>,
  img: () => null,
};

/**
 * A clean, print-optimized rendering of a report — no app chrome. Designed as a
 * light document so the on-screen view faithfully previews the saved PDF, and
 * `@media print` (see globals.css) tightens margins / page breaks. Opened in a
 * new tab by "Download PDF"; auto-triggers the browser's print → save-as-PDF
 * once the report is rendered (unless `?preview=1`, used for inspection).
 */
export function PrintReport({ id }: { id: string }) {
  const fetched = useApi((s) => getSession(id, s), [id]);
  const [model, setModel] = useState<string | null>(null);

  useEffect(() => {
    const ctrl = new AbortController();
    getLLMConfig(ctrl.signal)
      .then((c) => setModel(c.model))
      .catch(() => setModel(null));
    return () => ctrl.abort();
  }, []);

  const report = fetched.data?.report_md ?? null;

  // Auto-open the print dialog once the document is on the page.
  useEffect(() => {
    if (!report) return;
    const preview =
      typeof window !== "undefined" &&
      new URLSearchParams(window.location.search).get("preview");
    if (preview) return;
    const t = setTimeout(() => window.print(), 500);
    return () => clearTimeout(t);
  }, [report]);

  if (fetched.loading) {
    return (
      <div className="hp-print-page">
        <p className="hp-print-status">Loading report…</p>
      </div>
    );
  }
  if (fetched.error || !fetched.data) {
    return (
      <div className="hp-print-page">
        <p className="hp-print-status">
          {fetched.error ?? "Engagement not found."}
        </p>
      </div>
    );
  }

  const session: Session = fetched.data;

  if (!report) {
    return (
      <div className="hp-print-page">
        <p className="hp-print-status">
          No report has been generated for this engagement yet.
        </p>
      </div>
    );
  }

  return (
    <div className="hp-print-page">
      <div className="hp-print-doc">
        <div className="hp-print-actions hp-print-noprint">
          <button
            type="button"
            className="hp-print-btn"
            onClick={() => window.print()}
          >
            Save as PDF
          </button>
          <a className="hp-print-btn ghost" href={`/engagement/${id}/report`}>
            ← back to report
          </a>
        </div>

        <header className="hp-print-titleblock">
          <div className="hp-print-eyebrow">Penetration Test Report</div>
          <h1 className="hp-print-title">{session.label}</h1>
          <dl className="hp-print-meta">
            <div>
              <dt>Target / Goal</dt>
              <dd>
                {session.goal}
                {session.target_type ? ` · ${session.target_type}` : ""}
              </dd>
            </div>
            <div>
              <dt>Date</dt>
              <dd>{fmtDate(session.report_generated_at)}</dd>
            </div>
            <div>
              <dt>Generated by</dt>
              <dd>{model ?? "the configured model"}</dd>
            </div>
          </dl>
        </header>

        <div className="hp-print-body">
          <ReactMarkdown
            remarkPlugins={[remarkGfm]}
            rehypePlugins={[rehypeSanitize]}
            components={components}
          >
            {report}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
}
